{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle\n",
    "\n",
    "\n",
    "with open('coord_list.pkl', 'rb') as f:\n",
    "    data = pickle.load(f)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "astropy.coordinates.sky_coordinate.SkyCoord"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "type(data[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "from astroquery.simbad import Simbad\n",
    "from astroquery.xmatch import XMatch\n",
    "from astropy import units as u\n",
    "from astropy.table import Table\n",
    "from astropy.coordinates import SkyCoord"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<i>Table length=3074</i>\n",
       "<table id=\"table140179936209496\" class=\"table-striped table-bordered table-condensed\">\n",
       "<thead><tr><th>RA</th><th>Dec</th></tr></thead>\n",
       "<thead><tr><th>float64</th><th>float64</th></tr></thead>\n",
       "<tr><td>88.69424375463352</td><td>-6.4776284709998615</td></tr>\n",
       "<tr><td>81.57637442813676</td><td>-6.327234144349591</td></tr>\n",
       "<tr><td>85.51903637148102</td><td>-6.408033712573103</td></tr>\n",
       "<tr><td>90.1800004991527</td><td>-6.512782051634536</td></tr>\n",
       "<tr><td>87.95891218259771</td><td>-6.46192491980695</td></tr>\n",
       "<tr><td>85.25721850140215</td><td>-6.402046923892316</td></tr>\n",
       "<tr><td>86.58262856929026</td><td>-6.431619801002863</td></tr>\n",
       "<tr><td>86.6361400834329</td><td>-6.432196844615628</td></tr>\n",
       "<tr><td>91.37104525614362</td><td>-6.538896770370073</td></tr>\n",
       "<tr><td>90.94204151153852</td><td>-6.52889892496681</td></tr>\n",
       "<tr><td>...</td><td>...</td></tr>\n",
       "<tr><td>91.53389134297514</td><td>-17.493113605122506</td></tr>\n",
       "<tr><td>91.01407735867605</td><td>-17.677703263699893</td></tr>\n",
       "<tr><td>89.91557906274232</td><td>-17.591994311057974</td></tr>\n",
       "<tr><td>86.4411543380268</td><td>-17.416418586094327</td></tr>\n",
       "<tr><td>85.86788386195856</td><td>-17.67418966703596</td></tr>\n",
       "<tr><td>88.15611876106001</td><td>-17.235023035398388</td></tr>\n",
       "<tr><td>89.43810852805301</td><td>-17.473151810945776</td></tr>\n",
       "<tr><td>80.4586084641803</td><td>-16.773452010465515</td></tr>\n",
       "<tr><td>87.9936909010722</td><td>-17.754823417982706</td></tr>\n",
       "<tr><td>81.24946040126531</td><td>-17.44843737957598</td></tr>\n",
       "</table>"
      ],
      "text/plain": [
       "<Table length=3074>\n",
       "        RA                Dec        \n",
       "     float64            float64      \n",
       "----------------- -------------------\n",
       "88.69424375463352 -6.4776284709998615\n",
       "81.57637442813676  -6.327234144349591\n",
       "85.51903637148102  -6.408033712573103\n",
       " 90.1800004991527  -6.512782051634536\n",
       "87.95891218259771   -6.46192491980695\n",
       "85.25721850140215  -6.402046923892316\n",
       "86.58262856929026  -6.431619801002863\n",
       " 86.6361400834329  -6.432196844615628\n",
       "91.37104525614362  -6.538896770370073\n",
       "90.94204151153852   -6.52889892496681\n",
       "              ...                 ...\n",
       "91.53389134297514 -17.493113605122506\n",
       "91.01407735867605 -17.677703263699893\n",
       "89.91557906274232 -17.591994311057974\n",
       " 86.4411543380268 -17.416418586094327\n",
       "85.86788386195856  -17.67418966703596\n",
       "88.15611876106001 -17.235023035398388\n",
       "89.43810852805301 -17.473151810945776\n",
       " 80.4586084641803 -16.773452010465515\n",
       " 87.9936909010722 -17.754823417982706\n",
       "81.24946040126531  -17.44843737957598"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ra = []\n",
    "dec = []\n",
    "for coord in data:\n",
    "    ra.append(coord.ra.value)\n",
    "    dec.append(coord.dec.value)\n",
    "tab = Table([ra, dec], names=('RA', 'Dec'))\n",
    "tab"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "tab.write('test.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "xmatch_tab = XMatch.query(cat1=open('test.csv'), \n",
    "                          cat2='SIMBAD', max_distance=0.5* u.arcsec,\n",
    "                          colRA1='RA', colDec1='Dec')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<i>Table length=42</i>\n",
       "<table id=\"table140101891441328\" class=\"table-striped table-bordered table-condensed\">\n",
       "<thead><tr><th>angDist</th><th>RA</th><th>Dec</th><th>main_id</th><th>ra</th><th>dec</th><th>coo_err_maj</th><th>coo_err_min</th><th>coo_err_angle</th><th>nbref</th><th>ra_sexa</th><th>dec_sexa</th><th>main_type</th><th>other_types</th><th>radvel</th><th>redshift</th><th>sp_type</th><th>morph_type</th><th>plx</th><th>pmra</th><th>pmdec</th><th>size_maj</th><th>size_min</th><th>size_angle</th><th>B</th><th>V</th><th>R</th><th>J</th><th>H</th><th>K</th><th>u</th><th>g</th><th>r</th><th>i</th><th>z</th></tr></thead>\n",
       "<thead><tr><th>float64</th><th>float64</th><th>float64</th><th>str21</th><th>float64</th><th>float64</th><th>float64</th><th>float64</th><th>int64</th><th>int64</th><th>str14</th><th>str14</th><th>str8</th><th>str65</th><th>float64</th><th>float64</th><th>str8</th><th>int64</th><th>float64</th><th>float64</th><th>float64</th><th>int64</th><th>int64</th><th>int64</th><th>float64</th><th>float64</th><th>float64</th><th>float64</th><th>float64</th><th>float64</th><th>float64</th><th>float64</th><th>float64</th><th>float64</th><th>float64</th></tr></thead>\n",
       "<tr><td>0.203009</td><td>84.43530168510243</td><td>-6.843529616368494</td><td>V* V589 Ori</td><td>84.4353419638</td><td>-6.8434898589</td><td>0.0</td><td>0.0</td><td>90</td><td>24</td><td>05 37 44.48207</td><td>-06 50 36.5635</td><td>Orion_V*</td><td>Or*|Em*|V* |*iN|IR |pr*|Y*O|Y*O|*  |Y*O|X  |Em*|Em*|Em*|*  |*  |*</td><td>23.047</td><td>7.7e-05</td><td>M1.0</td><td>--</td><td>2.4781</td><td>-0.23</td><td>0.1</td><td>--</td><td>--</td><td>--</td><td>16.91</td><td>16.124</td><td>--</td><td>12.283</td><td>11.474</td><td>11.207</td><td>18.459</td><td>17.088</td><td>15.554</td><td>14.736</td><td>14.32</td></tr>\n",
       "<tr><td>0.193438</td><td>82.83908972737889</td><td>-7.39508036763199</td><td>WDS J05314-0724B</td><td>82.8390416667</td><td>-7.3950555556</td><td>--</td><td>--</td><td>172</td><td>1</td><td>05 31 21.37</td><td>-07 23 42.2</td><td>*in**</td><td>** |*  |*i*</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.186806</td><td>82.96340914341795</td><td>-7.716174655284498</td><td>HD  36513</td><td>82.9634607631</td><td>-7.7161659339</td><td>0.0</td><td>0.0</td><td>90</td><td>16</td><td>05 31 51.23058</td><td>-07 42 58.1974</td><td>Star</td><td>*  |IR</td><td>--</td><td>--</td><td>B9V</td><td>--</td><td>2.5365</td><td>0.53</td><td>-0.38</td><td>--</td><td>--</td><td>--</td><td>9.55</td><td>9.53</td><td>--</td><td>9.48</td><td>9.487</td><td>9.448</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.458512</td><td>90.73153127907604</td><td>-8.16726160830511</td><td>TYC 5349-595-1</td><td>90.7316437665</td><td>-8.1673234442</td><td>0.0</td><td>0.0</td><td>90</td><td>0</td><td>06 02 55.59450</td><td>-08 10 02.3644</td><td>Star</td><td>*  |IR</td><td>-23.53</td><td>-7.8e-05</td><td>--</td><td>--</td><td>1.4208</td><td>-19.9</td><td>-34.57</td><td>--</td><td>--</td><td>--</td><td>11.76</td><td>11.17</td><td>--</td><td>10.16</td><td>9.877</td><td>9.804</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.358169</td><td>82.44963317006741</td><td>-8.958779487270053</td><td>TYC 5333-958-1</td><td>82.4497255005</td><td>-8.9588192409</td><td>0.001</td><td>0.001</td><td>90</td><td>0</td><td>05 29 47.93412</td><td>-08 57 31.7493</td><td>Star</td><td>*  |IR</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>-3.7</td><td>-6.3</td><td>--</td><td>--</td><td>--</td><td>11.19</td><td>10.54</td><td>--</td><td>9.356</td><td>9.022</td><td>8.931</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.161367</td><td>82.81358487686472</td><td>-9.778893610238542</td><td>TYC 5337-151-1</td><td>82.8135789489</td><td>-9.7788491684</td><td>0.0</td><td>0.0</td><td>90</td><td>0</td><td>05 31 15.25895</td><td>-09 46 43.8570</td><td>Star</td><td>*  |*  |IR</td><td>14.31</td><td>4.8e-05</td><td>--</td><td>--</td><td>1.2632</td><td>0.23</td><td>-14.83</td><td>--</td><td>--</td><td>--</td><td>12.44</td><td>12.14</td><td>--</td><td>11.583</td><td>11.363</td><td>11.329</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.32137</td><td>90.56210040886707</td><td>-10.016488250896241</td><td>BD-10  1351</td><td>90.5620212909</td><td>-10.0165318252</td><td>0.0</td><td>0.0</td><td>90</td><td>29</td><td>06 02 14.88511</td><td>-10 00 59.5146</td><td>Ae*</td><td>V* |Em*|IR |*  |pr*|Ir*|Ae*</td><td>--</td><td>--</td><td>B3V[e]</td><td>--</td><td>1.1191</td><td>-1.75</td><td>1.79</td><td>--</td><td>--</td><td>--</td><td>10.54</td><td>10.4</td><td>--</td><td>9.193</td><td>8.334</td><td>7.464</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.23105</td><td>84.44324918195512</td><td>-9.962511744917638</td><td>CRTS J053746.3-095745</td><td>84.4432840201</td><td>-9.9625659829</td><td>0.0</td><td>0.0</td><td>90</td><td>1</td><td>05 37 46.38816</td><td>-09 57 45.2375</td><td>RRLyr</td><td>RR*</td><td>--</td><td>--</td><td>--</td><td>--</td><td>0.1203</td><td>5.43</td><td>-6.62</td><td>--</td><td>--</td><td>--</td><td>--</td><td>15.42</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.401938</td><td>91.1418590744326</td><td>-10.0503999071495</td><td>HD  41404</td><td>91.1419530529</td><td>-10.0504623783</td><td>0.0</td><td>0.0</td><td>90</td><td>6</td><td>06 04 34.06873</td><td>-10 03 01.6646</td><td>Star</td><td>*  |IR</td><td>39.32</td><td>0.000131</td><td>K0III</td><td>--</td><td>2.973</td><td>-3.2</td><td>-4.74</td><td>--</td><td>--</td><td>--</td><td>9.73</td><td>8.58</td><td>--</td><td>6.687</td><td>6.16</td><td>6.023</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.472792</td><td>87.83748547225503</td><td>-10.215239601860475</td><td>TYC 5351-132-1</td><td>87.8374145833</td><td>-10.2151283333</td><td>0.001</td><td>0.001</td><td>0</td><td>0</td><td>05 51 20.9795</td><td>-10 12 54.462</td><td>Star</td><td>*  |*  |IR</td><td>--</td><td>--</td><td>--</td><td>--</td><td>3.18</td><td>6.99</td><td>0.48</td><td>--</td><td>--</td><td>--</td><td>12.95</td><td>12.21</td><td>--</td><td>10.801</td><td>10.516</td><td>10.431</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr>\n",
       "<tr><td>0.466013</td><td>88.00594688049023</td><td>-15.506182261008439</td><td>HD  39441</td><td>88.0060731591</td><td>-15.5061380999</td><td>0.0</td><td>0.0</td><td>90</td><td>6</td><td>05 52 01.45756</td><td>-15 30 22.0972</td><td>Star</td><td>*  |UV |IR</td><td>--</td><td>--</td><td>A2III</td><td>--</td><td>4.9698</td><td>-5.86</td><td>11.44</td><td>--</td><td>--</td><td>--</td><td>7.21</td><td>7.09</td><td>--</td><td>6.761</td><td>6.74</td><td>6.666</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.372611</td><td>82.83992438159807</td><td>-15.668449516057322</td><td>ASAS J053122-1540.1</td><td>82.8399263795</td><td>-15.6683460308</td><td>0.0</td><td>0.0</td><td>90</td><td>4</td><td>05 31 21.58233</td><td>-15 40 06.0457</td><td>EB*</td><td>** |IR |EB?|*  |WU*</td><td>--</td><td>--</td><td>--</td><td>--</td><td>1.429</td><td>-1.76</td><td>-6.54</td><td>--</td><td>--</td><td>--</td><td>--</td><td>13.06</td><td>--</td><td>11.813</td><td>11.51</td><td>11.424</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.471019</td><td>81.2368523449491</td><td>-15.69419515608007</td><td>TYC 5915-613-2</td><td>81.2367333333</td><td>-15.6942583333</td><td>0.018</td><td>0.017</td><td>90</td><td>0</td><td>05 24 56.816</td><td>-15 41 39.33</td><td>Star</td><td>*</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>0.4</td><td>-1.0</td><td>--</td><td>--</td><td>--</td><td>12.11</td><td>11.22</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.385164</td><td>80.59315721085126</td><td>-15.782260744387479</td><td>UCAC2  25919789</td><td>80.593214296</td><td>-15.7823525551</td><td>0.0</td><td>0.0</td><td>90</td><td>0</td><td>05 22 22.37143</td><td>-15 46 56.4692</td><td>Star</td><td>*  |IR</td><td>49.948</td><td>0.000167</td><td>--</td><td>--</td><td>0.9238</td><td>-0.28</td><td>4.44</td><td>--</td><td>--</td><td>--</td><td>13.07</td><td>11.91</td><td>11.61</td><td>9.799</td><td>9.205</td><td>9.1</td><td>--</td><td>12.46</td><td>11.58</td><td>11.17</td><td>--</td></tr>\n",
       "<tr><td>0.263445</td><td>80.53365868821354</td><td>-15.861969394338473</td><td>CRTS J052208.0-155143</td><td>80.5337062999</td><td>-15.8620264704</td><td>0.0</td><td>0.0</td><td>90</td><td>1</td><td>05 22 08.08951</td><td>-15 51 43.2953</td><td>EB*</td><td>WU*</td><td>--</td><td>--</td><td>--</td><td>--</td><td>0.593</td><td>-1.65</td><td>-4.22</td><td>--</td><td>--</td><td>--</td><td>--</td><td>13.77</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.076972</td><td>83.85793500205841</td><td>-15.986743650402396</td><td>TYC 5916-742-1</td><td>83.8579442552</td><td>-15.9867242076</td><td>0.0</td><td>0.0</td><td>90</td><td>0</td><td>05 35 25.90662</td><td>-15 59 12.2071</td><td>Star</td><td>*  |IR</td><td>57.97</td><td>0.000193</td><td>--</td><td>--</td><td>0.3468</td><td>-4.96</td><td>-2.28</td><td>--</td><td>--</td><td>--</td><td>12.43</td><td>11.17</td><td>--</td><td>8.665</td><td>7.858</td><td>7.658</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.302549</td><td>80.63368697644933</td><td>-16.047896063628382</td><td>CRTS J052232.0-160252</td><td>80.6336067461</td><td>-16.0479294992</td><td>0.0</td><td>0.0</td><td>90</td><td>2</td><td>05 22 32.06562</td><td>-16 02 52.5462</td><td>EB*</td><td>WU*</td><td>--</td><td>--</td><td>--</td><td>--</td><td>0.6253</td><td>-3.13</td><td>4.61</td><td>--</td><td>--</td><td>--</td><td>--</td><td>16.26</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.273088</td><td>90.91248664759448</td><td>-17.450512357206406</td><td>TYC 5936-1297-1</td><td>90.9125141338</td><td>-17.4504411755</td><td>0.0</td><td>0.0</td><td>90</td><td>0</td><td>06 03 39.00339</td><td>-17 27 01.5882</td><td>Star</td><td>*  |*  |IR</td><td>10.34</td><td>3.4e-05</td><td>--</td><td>--</td><td>2.2665</td><td>3.45</td><td>-9.03</td><td>--</td><td>--</td><td>--</td><td>13.0</td><td>12.0</td><td>--</td><td>10.957</td><td>10.702</td><td>10.636</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.373965</td><td>85.06928969069766</td><td>-17.104562982339836</td><td>HD  37759</td><td>85.0692972806</td><td>-17.1044593567</td><td>0.0</td><td>0.0</td><td>90</td><td>3</td><td>05 40 16.63135</td><td>-17 06 16.0537</td><td>Star</td><td>*  |IR</td><td>--</td><td>--</td><td>A3II/III</td><td>--</td><td>4.4647</td><td>1.77</td><td>-17.15</td><td>--</td><td>--</td><td>--</td><td>8.43</td><td>8.23</td><td>--</td><td>7.865</td><td>7.868</td><td>7.774</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "<tr><td>0.495792</td><td>90.70905486499359</td><td>-17.39662118615193</td><td>BD-17  1338</td><td>90.7089195425</td><td>-17.3966690563</td><td>0.0</td><td>0.0</td><td>90</td><td>0</td><td>06 02 50.14069</td><td>-17 23 48.0086</td><td>Star</td><td>*  |IR</td><td>59.22</td><td>0.000198</td><td>--</td><td>--</td><td>1.0979</td><td>1.43</td><td>4.9</td><td>--</td><td>--</td><td>--</td><td>11.33</td><td>10.2</td><td>--</td><td>8.12</td><td>7.58</td><td>7.4</td><td>--</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>\n",
       "</table>"
      ],
      "text/plain": [
       "<Table length=42>\n",
       "angDist          RA                Dec         ...    r       i       z   \n",
       "float64       float64            float64       ... float64 float64 float64\n",
       "-------- ----------------- ------------------- ... ------- ------- -------\n",
       "0.203009 84.43530168510243  -6.843529616368494 ...  15.554  14.736   14.32\n",
       "0.193438 82.83908972737889   -7.39508036763199 ...      --      --      --\n",
       "0.186806 82.96340914341795  -7.716174655284498 ...      --      --      --\n",
       "0.458512 90.73153127907604   -8.16726160830511 ...      --      --      --\n",
       "0.358169 82.44963317006741  -8.958779487270053 ...      --      --      --\n",
       "0.161367 82.81358487686472  -9.778893610238542 ...      --      --      --\n",
       " 0.32137 90.56210040886707 -10.016488250896241 ...      --      --      --\n",
       " 0.23105 84.44324918195512  -9.962511744917638 ...      --      --      --\n",
       "0.401938  91.1418590744326   -10.0503999071495 ...      --      --      --\n",
       "0.472792 87.83748547225503 -10.215239601860475 ...      --      --      --\n",
       "     ...               ...                 ... ...     ...     ...     ...\n",
       "0.466013 88.00594688049023 -15.506182261008439 ...      --      --      --\n",
       "0.372611 82.83992438159807 -15.668449516057322 ...      --      --      --\n",
       "0.471019  81.2368523449491  -15.69419515608007 ...      --      --      --\n",
       "0.385164 80.59315721085126 -15.782260744387479 ...   11.58   11.17      --\n",
       "0.263445 80.53365868821354 -15.861969394338473 ...      --      --      --\n",
       "0.076972 83.85793500205841 -15.986743650402396 ...      --      --      --\n",
       "0.302549 80.63368697644933 -16.047896063628382 ...      --      --      --\n",
       "0.273088 90.91248664759448 -17.450512357206406 ...      --      --      --\n",
       "0.373965 85.06928969069766 -17.104562982339836 ...      --      --      --\n",
       "0.495792 90.70905486499359  -17.39662118615193 ...      --      --      --"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "xmatch_tab"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "orig_coord = SkyCoord(ra=tab['RA']*u.degree, dec=tab['Dec']*u.degree)\n",
    "xmatch_coord = SkyCoord(ra=xmatch_tab['RA']*u.degree, dec=xmatch_tab['Dec']*u.degree)\n",
    "idx, d2d, d3d = orig_coord.match_to_catalog_sky(xmatch_coord)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "ind = d2d < 0.5 * u.arcsec"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<i>Table length=42</i>\n",
       "<table id=\"table140101891565160\" class=\"table-striped table-bordered table-condensed\">\n",
       "<thead><tr><th>RA</th><th>Dec</th></tr></thead>\n",
       "<thead><tr><th>float64</th><th>float64</th></tr></thead>\n",
       "<tr><td>84.43530168510243</td><td>-6.843529616368494</td></tr>\n",
       "<tr><td>82.83908972737889</td><td>-7.39508036763199</td></tr>\n",
       "<tr><td>82.96340914341795</td><td>-7.716174655284498</td></tr>\n",
       "<tr><td>90.73153127907604</td><td>-8.16726160830511</td></tr>\n",
       "<tr><td>82.44963317006741</td><td>-8.958779487270053</td></tr>\n",
       "<tr><td>82.81358487686472</td><td>-9.778893610238542</td></tr>\n",
       "<tr><td>90.56210040886707</td><td>-10.016488250896241</td></tr>\n",
       "<tr><td>84.44324918195512</td><td>-9.962511744917638</td></tr>\n",
       "<tr><td>91.1418590744326</td><td>-10.0503999071495</td></tr>\n",
       "<tr><td>87.83748547225503</td><td>-10.215239601860475</td></tr>\n",
       "<tr><td>...</td><td>...</td></tr>\n",
       "<tr><td>88.00594688049023</td><td>-15.506182261008439</td></tr>\n",
       "<tr><td>82.83992438159807</td><td>-15.668449516057322</td></tr>\n",
       "<tr><td>81.2368523449491</td><td>-15.69419515608007</td></tr>\n",
       "<tr><td>80.59315721085126</td><td>-15.782260744387479</td></tr>\n",
       "<tr><td>80.53365868821354</td><td>-15.861969394338473</td></tr>\n",
       "<tr><td>83.85793500205841</td><td>-15.986743650402396</td></tr>\n",
       "<tr><td>80.63368697644933</td><td>-16.047896063628382</td></tr>\n",
       "<tr><td>90.91248664759448</td><td>-17.450512357206406</td></tr>\n",
       "<tr><td>85.06928969069766</td><td>-17.104562982339836</td></tr>\n",
       "<tr><td>90.70905486499359</td><td>-17.39662118615193</td></tr>\n",
       "</table>"
      ],
      "text/plain": [
       "<Table length=42>\n",
       "        RA                Dec        \n",
       "     float64            float64      \n",
       "----------------- -------------------\n",
       "84.43530168510243  -6.843529616368494\n",
       "82.83908972737889   -7.39508036763199\n",
       "82.96340914341795  -7.716174655284498\n",
       "90.73153127907604   -8.16726160830511\n",
       "82.44963317006741  -8.958779487270053\n",
       "82.81358487686472  -9.778893610238542\n",
       "90.56210040886707 -10.016488250896241\n",
       "84.44324918195512  -9.962511744917638\n",
       " 91.1418590744326   -10.0503999071495\n",
       "87.83748547225503 -10.215239601860475\n",
       "              ...                 ...\n",
       "88.00594688049023 -15.506182261008439\n",
       "82.83992438159807 -15.668449516057322\n",
       " 81.2368523449491  -15.69419515608007\n",
       "80.59315721085126 -15.782260744387479\n",
       "80.53365868821354 -15.861969394338473\n",
       "83.85793500205841 -15.986743650402396\n",
       "80.63368697644933 -16.047896063628382\n",
       "90.91248664759448 -17.450512357206406\n",
       "85.06928969069766 -17.104562982339836\n",
       "90.70905486499359  -17.39662118615193"
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "tab[ind]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "orig_coord = SkyCoord(ra=tab['RA']*u.degree, dec=tab['Dec']*u.degree)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "search_radius = [2 * u.arcsec] * len(orig_coord)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): '5:54:46.6185 -6:28:39.4625': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 6 raised an error (recorded in the `errors` attribute of the result table): '6:00:43.2001 -6:30:46.0154': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 9 raised an error (recorded in the `errors` attribute of the result table): '5:46:19.8309 -6:25:53.8313': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 12 raised an error (recorded in the `errors` attribute of the result table): '6:03:46.09 -6:31:44.0361': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 15 raised an error (recorded in the `errors` attribute of the result table): '5:44:24.0825 -6:25:19.1065': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 23 raised an error (recorded in the `errors` attribute of the result table): '5:44:42.9476 -6:25:26.0638': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 32 raised an error (recorded in the `errors` attribute of the result table): '6:00:22.2388 -6:33:23.872': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 45 raised an error (recorded in the `errors` attribute of the result table): '5:41:18.6673 -6:30:07.2495': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 55 raised an error (recorded in the `errors` attribute of the result table): '5:41:19.3054 -6:32:59.9194': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 65 raised an error (recorded in the `errors` attribute of the result table): '5:40:55.6155 -6:38:47.3044': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 73 raised an error (recorded in the `errors` attribute of the result table): '5:46:12.6611 -6:42:57.5814': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 87 raised an error (recorded in the `errors` attribute of the result table): '6:07:08.4333 -6:55:03.2392': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 93 raised an error (recorded in the `errors` attribute of the result table): '5:46:03.708 -6:48:18.5233': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 99 raised an error (recorded in the `errors` attribute of the result table): '6:05:47.5077 -6:53:34.6957': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 103 raised an error (recorded in the `errors` attribute of the result table): '6:01:34.973 -6:49:00.8083': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 108 raised an error (recorded in the `errors` attribute of the result table): '6:02:16.9475 -6:51:08.7275': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 119 raised an error (recorded in the `errors` attribute of the result table): '6:04:33.5953 -6:57:14.2722': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 132 raised an error (recorded in the `errors` attribute of the result table): '5:48:22.2628 -6:59:04.8152': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 148 raised an error (recorded in the `errors` attribute of the result table): '5:41:38.0422 -6:51:24.2334': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 157 raised an error (recorded in the `errors` attribute of the result table): '6:04:54.9376 -7:03:12.8796': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 163 raised an error (recorded in the `errors` attribute of the result table): '5:40:01.3065 -6:57:11.7548': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 167 raised an error (recorded in the `errors` attribute of the result table): '6:05:59.5807 -7:01:23.0425': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 174 raised an error (recorded in the `errors` attribute of the result table): '5:32:53.2078 -7:02:59.9611': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 182 raised an error (recorded in the `errors` attribute of the result table): '5:57:49.3457 -6:48:49.8949': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 185 raised an error (recorded in the `errors` attribute of the result table): '5:58:22.1465 -7:03:49.772': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 188 raised an error (recorded in the `errors` attribute of the result table): '5:44:06.7162 -7:09:01.5432': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 198 raised an error (recorded in the `errors` attribute of the result table): '5:43:36.3152 -7:10:07.0705': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 203 raised an error (recorded in the `errors` attribute of the result table): '5:55:29.4151 -6:47:09.457': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 211 raised an error (recorded in the `errors` attribute of the result table): '5:31:23.6858 -7:09:27.3845': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 219 raised an error (recorded in the `errors` attribute of the result table): '6:07:06.7503 -7:25:31.8716': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 235 raised an error (recorded in the `errors` attribute of the result table): '5:50:52.2192 -7:23:19.6157': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 247 raised an error (recorded in the `errors` attribute of the result table): '6:04:34.6992 -7:30:45.2409': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 251 raised an error (recorded in the `errors` attribute of the result table): '5:46:12.1647 -7:19:05.0352': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 255 raised an error (recorded in the `errors` attribute of the result table): '5:45:46.2329 -7:25:43.3861': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 259 raised an error (recorded in the `errors` attribute of the result table): '5:46:18.8278 -7:23:51.1373': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 263 raised an error (recorded in the `errors` attribute of the result table): '6:03:44.3869 -7:33:13.604': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 285 raised an error (recorded in the `errors` attribute of the result table): '5:32:25.9788 -7:26:44.8969': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 288 raised an error (recorded in the `errors` attribute of the result table): '6:02:35.9626 -7:34:35.6695': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 293 raised an error (recorded in the `errors` attribute of the result table): '6:05:05.9639 -7:37:18.2763': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 302 raised an error (recorded in the `errors` attribute of the result table): '5:55:01.914 -7:35:40.9923': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 305 raised an error (recorded in the `errors` attribute of the result table): '5:48:43.0629 -7:28:02.7062': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 313 raised an error (recorded in the `errors` attribute of the result table): '5:31:59.9293 -7:24:25.5454': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 315 raised an error (recorded in the `errors` attribute of the result table): '5:43:54.14 -7:33:27.4551': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 323 raised an error (recorded in the `errors` attribute of the result table): '5:57:55.5832 -7:34:47.8306': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 330 raised an error (recorded in the `errors` attribute of the result table): '5:31:07.7834 -7:31:37.5784': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 338 raised an error (recorded in the `errors` attribute of the result table): '5:47:37.1533 -7:38:13.8004': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 354 raised an error (recorded in the `errors` attribute of the result table): '5:29:23.0097 -7:35:50.4853': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 357 raised an error (recorded in the `errors` attribute of the result table): '5:26:30.6418 -7:34:41.9677': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 360 raised an error (recorded in the `errors` attribute of the result table): '6:05:22.7262 -7:53:05.9215': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 366 raised an error (recorded in the `errors` attribute of the result table): '5:51:03.6421 -7:35:39.4492': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 372 raised an error (recorded in the `errors` attribute of the result table): '6:05:46.2222 -7:49:02.1365': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 374 raised an error (recorded in the `errors` attribute of the result table): '5:45:40.7488 -7:41:08.1906': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 379 raised an error (recorded in the `errors` attribute of the result table): '5:59:59.8441 -7:55:37.6416': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 381 raised an error (recorded in the `errors` attribute of the result table): '5:30:06.6286 -7:18:35.6607': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 385 raised an error (recorded in the `errors` attribute of the result table): '6:04:03.6071 -7:56:43.232': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 392 raised an error (recorded in the `errors` attribute of the result table): '6:00:55.4677 -7:58:45.1929': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 404 raised an error (recorded in the `errors` attribute of the result table): '6:01:48.8443 -8:03:03.8549': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 414 raised an error (recorded in the `errors` attribute of the result table): '5:32:41.7544 -7:51:28.5678': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 420 raised an error (recorded in the `errors` attribute of the result table): '6:03:35.1878 -8:06:02.0825': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 423 raised an error (recorded in the `errors` attribute of the result table): '5:57:49.1351 -8:05:35.21': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 427 raised an error (recorded in the `errors` attribute of the result table): '6:03:44.2203 -8:04:22.2819': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 439 raised an error (recorded in the `errors` attribute of the result table): '5:34:25.5409 -7:59:45.9488': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 444 raised an error (recorded in the `errors` attribute of the result table): '5:37:27.8187 -8:00:49.8493': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 468 raised an error (recorded in the `errors` attribute of the result table): '5:31:31.8753 -8:08:58.1762': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 473 raised an error (recorded in the `errors` attribute of the result table): '5:52:09.7131 -8:15:09.356': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 480 raised an error (recorded in the `errors` attribute of the result table): '5:57:59.4528 -8:21:54.1727': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 493 raised an error (recorded in the `errors` attribute of the result table): '5:58:36.1121 -8:22:53.9066': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 501 raised an error (recorded in the `errors` attribute of the result table): '5:50:17.0742 -8:23:36.5537': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 503 raised an error (recorded in the `errors` attribute of the result table): '5:52:38.6509 -8:09:36.1061': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 510 raised an error (recorded in the `errors` attribute of the result table): '5:51:17.6021 -8:26:18.4644': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 514 raised an error (recorded in the `errors` attribute of the result table): '6:00:49.5903 -8:16:40.0262': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 516 raised an error (recorded in the `errors` attribute of the result table): '6:03:46.8335 -8:32:07.2869': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 518 raised an error (recorded in the `errors` attribute of the result table): '5:24:16.6469 -8:16:16.8974': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 525 raised an error (recorded in the `errors` attribute of the result table): '5:29:18.8373 -8:20:25.1641': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 541 raised an error (recorded in the `errors` attribute of the result table): '5:56:45.0774 -8:39:47.134': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 544 raised an error (recorded in the `errors` attribute of the result table): '5:46:00.3742 -8:31:11.892': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 552 raised an error (recorded in the `errors` attribute of the result table): '6:04:38.9091 -8:44:34.724': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 559 raised an error (recorded in the `errors` attribute of the result table): '5:58:14.336 -8:44:12.0222': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 565 raised an error (recorded in the `errors` attribute of the result table): '6:02:12.9171 -8:41:37.7323': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 572 raised an error (recorded in the `errors` attribute of the result table): '5:52:32.2682 -8:44:59.8645': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 578 raised an error (recorded in the `errors` attribute of the result table): '5:27:52.0167 -8:33:54.9608': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 583 raised an error (recorded in the `errors` attribute of the result table): '5:47:49.7984 -8:40:59.2733': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 593 raised an error (recorded in the `errors` attribute of the result table): '5:28:13.8045 -8:37:52.8216': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 597 raised an error (recorded in the `errors` attribute of the result table): '5:28:03.674 -8:40:18.5428': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 605 raised an error (recorded in the `errors` attribute of the result table): '5:51:25.6588 -8:52:09.0567': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 610 raised an error (recorded in the `errors` attribute of the result table): '5:35:05.9998 -8:44:08.4317': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 618 raised an error (recorded in the `errors` attribute of the result table): '5:56:04.9929 -8:56:43.1457': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 623 raised an error (recorded in the `errors` attribute of the result table): '5:22:51.2162 -8:43:41.965': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 631 raised an error (recorded in the `errors` attribute of the result table): '6:06:40.7675 -9:06:07.4004': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 637 raised an error (recorded in the `errors` attribute of the result table): '5:24:00.0726 -8:39:55.811': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 650 raised an error (recorded in the `errors` attribute of the result table): '6:06:58.3749 -9:07:22.1416': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 658 raised an error (recorded in the `errors` attribute of the result table): '5:24:25.0088 -8:45:42.9524': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 663 raised an error (recorded in the `errors` attribute of the result table): '5:37:52.2177 -8:58:03.4065': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 673 raised an error (recorded in the `errors` attribute of the result table): '6:01:29.2563 -9:07:25.5798': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 685 raised an error (recorded in the `errors` attribute of the result table): '5:47:10.2104 -9:08:27.3413': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 688 raised an error (recorded in the `errors` attribute of the result table): '5:34:53.3733 -9:02:48.5651': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 694 raised an error (recorded in the `errors` attribute of the result table): '6:01:21.434 -9:10:03.1232': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 698 raised an error (recorded in the `errors` attribute of the result table): '5:37:11.3435 -9:06:55.1523': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 703 raised an error (recorded in the `errors` attribute of the result table): '5:53:41.9848 -9:17:42.4057': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 708 raised an error (recorded in the `errors` attribute of the result table): '5:30:28.5884 -9:05:02.4385': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 711 raised an error (recorded in the `errors` attribute of the result table): '5:36:30.5052 -9:05:32.3889': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 715 raised an error (recorded in the `errors` attribute of the result table): '5:52:57.9198 -9:16:37.3207': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 730 raised an error (recorded in the `errors` attribute of the result table): '6:02:52.8541 -9:28:46.9649': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 738 raised an error (recorded in the `errors` attribute of the result table): '5:50:01.8876 -9:23:27.6186': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 740 raised an error (recorded in the `errors` attribute of the result table): '5:51:19.5216 -9:26:09.6465': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 742 raised an error (recorded in the `errors` attribute of the result table): '5:38:05.674 -9:16:21.2629': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 752 raised an error (recorded in the `errors` attribute of the result table): '5:35:56.0098 -9:21:13.2321': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 755 raised an error (recorded in the `errors` attribute of the result table): '6:00:45.8942 -9:33:34.1958': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 761 raised an error (recorded in the `errors` attribute of the result table): '5:25:06.4178 -9:13:18.2471': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 766 raised an error (recorded in the `errors` attribute of the result table): '5:25:16.9126 -9:13:53.512': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 770 raised an error (recorded in the `errors` attribute of the result table): '5:28:11.8192 -9:19:28.0712': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 779 raised an error (recorded in the `errors` attribute of the result table): '5:47:49.0469 -9:29:13.6592': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 781 raised an error (recorded in the `errors` attribute of the result table): '5:38:25.0442 -9:14:39.5031': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 791 raised an error (recorded in the `errors` attribute of the result table): '5:56:01.7025 -9:39:10.0786': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 794 raised an error (recorded in the `errors` attribute of the result table): '5:47:48.1706 -9:27:28.6333': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 799 raised an error (recorded in the `errors` attribute of the result table): '5:55:46.0747 -9:43:46.8366': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 802 raised an error (recorded in the `errors` attribute of the result table): '5:56:36.4287 -9:40:20.4618': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 806 raised an error (recorded in the `errors` attribute of the result table): '5:28:44.7065 -9:29:56.3946': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 814 raised an error (recorded in the `errors` attribute of the result table): '5:37:34.9921 -9:34:08.0259': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 820 raised an error (recorded in the `errors` attribute of the result table): '5:43:53.3434 -9:28:28.5713': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 825 raised an error (recorded in the `errors` attribute of the result table): '5:54:02.6077 -9:46:49.4173': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 828 raised an error (recorded in the `errors` attribute of the result table): '6:07:30.6358 -9:46:58.9726': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 834 raised an error (recorded in the `errors` attribute of the result table): '6:01:49.6607 -9:46:23.9903': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 838 raised an error (recorded in the `errors` attribute of the result table): '5:59:01.1278 -9:44:10.3107': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 842 raised an error (recorded in the `errors` attribute of the result table): '6:05:36.5501 -9:44:30.4541': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 847 raised an error (recorded in the `errors` attribute of the result table): '5:26:55.9108 -9:34:06.6331': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 854 raised an error (recorded in the `errors` attribute of the result table): '5:34:59.2385 -9:40:07.9531': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 857 raised an error (recorded in the `errors` attribute of the result table): '5:54:01.957 -9:51:06.8988': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 874 raised an error (recorded in the `errors` attribute of the result table): '5:45:33.5441 -9:52:24.072': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 881 raised an error (recorded in the `errors` attribute of the result table): '5:46:06.6171 -9:54:01.9199': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 887 raised an error (recorded in the `errors` attribute of the result table): '5:51:37.8837 -9:50:51.1859': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 895 raised an error (recorded in the `errors` attribute of the result table): '5:21:25.7167 -9:46:28.0244': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 900 raised an error (recorded in the `errors` attribute of the result table): '5:49:59.6803 -9:54:19.362': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 906 raised an error (recorded in the `errors` attribute of the result table): '5:49:55.1768 -9:59:12.0007': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 913 raised an error (recorded in the `errors` attribute of the result table): '6:06:10.6453 -10:06:27.1448': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 920 raised an error (recorded in the `errors` attribute of the result table): '5:21:29.3633 -9:39:37.3439': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 928 raised an error (recorded in the `errors` attribute of the result table): '5:40:26.4392 -10:00:29.6073': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 935 raised an error (recorded in the `errors` attribute of the result table): '5:48:20.9278 -10:05:54.7594': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 939 raised an error (recorded in the `errors` attribute of the result table): '6:03:27.472 -10:09:49.2621': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 944 raised an error (recorded in the `errors` attribute of the result table): '5:34:09.6733 -9:59:34.7145': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 957 raised an error (recorded in the `errors` attribute of the result table): '6:00:38.8029 -10:16:32.2714': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 961 raised an error (recorded in the `errors` attribute of the result table): '6:01:37.7956 -10:09:19.2177': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 965 raised an error (recorded in the `errors` attribute of the result table): '5:58:50.108 -10:10:01.1538': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 968 raised an error (recorded in the `errors` attribute of the result table): '5:51:56.7625 -10:09:29.783': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 971 raised an error (recorded in the `errors` attribute of the result table): '5:43:54.3848 -10:11:04.5784': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 981 raised an error (recorded in the `errors` attribute of the result table): '5:37:19.7584 -10:07:38.6717': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 986 raised an error (recorded in the `errors` attribute of the result table): '5:44:51.1542 -10:14:20.5122': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 990 raised an error (recorded in the `errors` attribute of the result table): '5:58:56.6341 -10:16:18.4375': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 994 raised an error (recorded in the `errors` attribute of the result table): '5:59:41.5971 -10:21:02.7389': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 996 raised an error (recorded in the `errors` attribute of the result table): '5:35:48.9947 -10:11:09.0201': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 998 raised an error (recorded in the `errors` attribute of the result table): '5:57:46.369 -10:17:26.3461': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1003 raised an error (recorded in the `errors` attribute of the result table): '6:02:44.5017 -10:16:04.5383': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1013 raised an error (recorded in the `errors` attribute of the result table): '5:31:31.9378 -10:09:13.4706': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1020 raised an error (recorded in the `errors` attribute of the result table): '6:03:30.5401 -10:26:40.8129': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1023 raised an error (recorded in the `errors` attribute of the result table): '5:42:00.0561 -10:18:39.7155': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1027 raised an error (recorded in the `errors` attribute of the result table): '5:44:13.9341 -10:20:24.9753': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1029 raised an error (recorded in the `errors` attribute of the result table): '6:00:51.3898 -10:28:15.037': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1034 raised an error (recorded in the `errors` attribute of the result table): '6:05:00.9803 -10:28:17.0472': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1038 raised an error (recorded in the `errors` attribute of the result table): '6:06:12.1692 -10:28:49.6203': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1042 raised an error (recorded in the `errors` attribute of the result table): '5:25:45.4878 -10:07:25.5397': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1046 raised an error (recorded in the `errors` attribute of the result table): '5:29:38.5767 -10:15:16.9531': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1049 raised an error (recorded in the `errors` attribute of the result table): '5:59:54.5383 -10:28:50.5337': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1052 raised an error (recorded in the `errors` attribute of the result table): '5:28:29.5906 -10:15:57.0752': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1054 raised an error (recorded in the `errors` attribute of the result table): '5:31:00.0281 -10:15:42.0941': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1057 raised an error (recorded in the `errors` attribute of the result table): '6:05:25.9091 -10:34:02.7258': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1064 raised an error (recorded in the `errors` attribute of the result table): '5:30:04.0167 -10:21:26.8709': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1071 raised an error (recorded in the `errors` attribute of the result table): '5:49:47.3832 -10:34:41.4704': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1075 raised an error (recorded in the `errors` attribute of the result table): '5:50:23.8947 -10:35:29.5459': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1079 raised an error (recorded in the `errors` attribute of the result table): '5:56:40.1311 -10:32:52.7114': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1084 raised an error (recorded in the `errors` attribute of the result table): '5:37:06.3276 -10:32:05.566': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1086 raised an error (recorded in the `errors` attribute of the result table): '6:07:15.4342 -10:41:01.1': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1090 raised an error (recorded in the `errors` attribute of the result table): '5:56:51.2754 -10:39:34.8636': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1093 raised an error (recorded in the `errors` attribute of the result table): '5:38:37.8236 -10:34:35.9214': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1096 raised an error (recorded in the `errors` attribute of the result table): '6:04:28.8998 -10:49:16.9583': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1099 raised an error (recorded in the `errors` attribute of the result table): '5:22:02.6074 -10:20:33.5777': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1108 raised an error (recorded in the `errors` attribute of the result table): '5:56:17.4881 -10:51:48.1564': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1112 raised an error (recorded in the `errors` attribute of the result table): '5:47:57.945 -10:45:25.9642': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1114 raised an error (recorded in the `errors` attribute of the result table): '5:47:42.8781 -9:51:59.13': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1118 raised an error (recorded in the `errors` attribute of the result table): '6:03:02.0754 -10:50:54.4284': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1126 raised an error (recorded in the `errors` attribute of the result table): '5:40:46.541 -10:40:25.474': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1130 raised an error (recorded in the `errors` attribute of the result table): '5:48:33.9123 -10:50:21.1677': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1134 raised an error (recorded in the `errors` attribute of the result table): '5:59:26.9922 -10:49:00.1195': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1136 raised an error (recorded in the `errors` attribute of the result table): '5:44:03.3229 -10:48:23.797': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1140 raised an error (recorded in the `errors` attribute of the result table): '5:33:12.4262 -10:40:44.0184': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1144 raised an error (recorded in the `errors` attribute of the result table): '5:59:22.5182 -10:56:16.7286': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1146 raised an error (recorded in the `errors` attribute of the result table): '5:55:55.5649 -10:58:50.0298': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1154 raised an error (recorded in the `errors` attribute of the result table): '5:32:48.9869 -10:45:27.9926': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1158 raised an error (recorded in the `errors` attribute of the result table): '5:59:04.3899 -11:00:51.3037': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1163 raised an error (recorded in the `errors` attribute of the result table): '5:46:09.0737 -10:56:22.3786': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1166 raised an error (recorded in the `errors` attribute of the result table): '5:29:16.7607 -10:49:40.0347': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1171 raised an error (recorded in the `errors` attribute of the result table): '5:22:17.5528 -10:42:26.3406': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1178 raised an error (recorded in the `errors` attribute of the result table): '5:52:20.3642 -11:04:11.2447': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1185 raised an error (recorded in the `errors` attribute of the result table): '5:59:41.3803 -11:09:07.6472': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1193 raised an error (recorded in the `errors` attribute of the result table): '5:52:15.8362 -11:10:45.6122': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1196 raised an error (recorded in the `errors` attribute of the result table): '5:38:02.0124 -11:02:34.989': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1205 raised an error (recorded in the `errors` attribute of the result table): '5:47:51.1853 -11:09:16.3636': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1212 raised an error (recorded in the `errors` attribute of the result table): '6:04:51.9567 -11:15:26.6939': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1217 raised an error (recorded in the `errors` attribute of the result table): '5:42:00.5259 -11:04:10.9192': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1219 raised an error (recorded in the `errors` attribute of the result table): '5:51:54.0234 -11:08:20.9936': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1224 raised an error (recorded in the `errors` attribute of the result table): '5:51:33.0225 -11:13:47.6596': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1234 raised an error (recorded in the `errors` attribute of the result table): '5:44:18.0902 -11:11:52.2686': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1236 raised an error (recorded in the `errors` attribute of the result table): '5:50:53.8174 -11:12:06.6459': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1240 raised an error (recorded in the `errors` attribute of the result table): '5:27:38.6057 -11:02:58.7372': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1246 raised an error (recorded in the `errors` attribute of the result table): '5:53:03.3144 -11:14:17.5927': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1256 raised an error (recorded in the `errors` attribute of the result table): '5:42:34.6258 -11:13:53.5921': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1262 raised an error (recorded in the `errors` attribute of the result table): '5:47:09.5771 -11:17:51.4356': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1273 raised an error (recorded in the `errors` attribute of the result table): '5:59:32.5649 -11:25:24.7682': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1283 raised an error (recorded in the `errors` attribute of the result table): '6:01:31.2192 -11:24:59.5484': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1290 raised an error (recorded in the `errors` attribute of the result table): '5:58:52.3918 -11:28:43.4164': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1292 raised an error (recorded in the `errors` attribute of the result table): '5:48:50.0253 -11:25:19.541': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1295 raised an error (recorded in the `errors` attribute of the result table): '6:03:53.249 -11:32:26.8872': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1299 raised an error (recorded in the `errors` attribute of the result table): '5:50:51.6315 -11:31:12.243': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1301 raised an error (recorded in the `errors` attribute of the result table): '5:51:32.4461 -11:31:22.3709': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1306 raised an error (recorded in the `errors` attribute of the result table): '5:36:09.4889 -11:22:34.7733': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1313 raised an error (recorded in the `errors` attribute of the result table): '6:00:34.9636 -11:36:11.4814': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1322 raised an error (recorded in the `errors` attribute of the result table): '5:35:09.9859 -11:27:40.9748': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1324 raised an error (recorded in the `errors` attribute of the result table): '6:06:37.9402 -11:37:53.1302': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1327 raised an error (recorded in the `errors` attribute of the result table): '5:52:38.494 -11:37:35.7506': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1332 raised an error (recorded in the `errors` attribute of the result table): '5:33:12.4284 -11:27:53.845': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1337 raised an error (recorded in the `errors` attribute of the result table): '5:47:41.9406 -11:38:37.0505': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1341 raised an error (recorded in the `errors` attribute of the result table): '6:06:15.7665 -11:45:38.8334': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1351 raised an error (recorded in the `errors` attribute of the result table): '5:52:21.2707 -11:45:44.0349': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1353 raised an error (recorded in the `errors` attribute of the result table): '5:28:46.1873 -11:29:17.8951': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1356 raised an error (recorded in the `errors` attribute of the result table): '5:22:47.6726 -11:26:22.1294': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1364 raised an error (recorded in the `errors` attribute of the result table): '5:48:43.9957 -11:44:17.2307': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1369 raised an error (recorded in the `errors` attribute of the result table): '6:03:38.883 -11:50:43.5386': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1376 raised an error (recorded in the `errors` attribute of the result table): '5:45:41.4029 -11:48:37.2885': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1380 raised an error (recorded in the `errors` attribute of the result table): '6:02:58.7719 -11:57:06.2149': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1392 raised an error (recorded in the `errors` attribute of the result table): '5:27:53.6734 -11:38:23.7659': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1395 raised an error (recorded in the `errors` attribute of the result table): '5:27:23.3285 -11:45:39.9877': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1410 raised an error (recorded in the `errors` attribute of the result table): '6:04:35.8842 -12:07:50.0944': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1419 raised an error (recorded in the `errors` attribute of the result table): '6:06:16.3712 -12:11:44.211': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1422 raised an error (recorded in the `errors` attribute of the result table): '5:43:21.765 -12:02:22.3493': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1428 raised an error (recorded in the `errors` attribute of the result table): '5:54:03.1242 -12:07:47.8057': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1431 raised an error (recorded in the `errors` attribute of the result table): '5:40:49.2083 -12:07:34.3844': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1443 raised an error (recorded in the `errors` attribute of the result table): '5:30:02.5868 -12:01:58.1857': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1449 raised an error (recorded in the `errors` attribute of the result table): '5:57:57.4875 -11:32:37.8814': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1456 raised an error (recorded in the `errors` attribute of the result table): '5:55:57.4582 -12:02:19.7481': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1462 raised an error (recorded in the `errors` attribute of the result table): '5:53:31.543 -12:19:26.4582': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1465 raised an error (recorded in the `errors` attribute of the result table): '5:40:35.2588 -12:09:59.9842': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1468 raised an error (recorded in the `errors` attribute of the result table): '5:47:57.4543 -12:14:34.9119': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1471 raised an error (recorded in the `errors` attribute of the result table): '5:37:17.5627 -12:09:36.0082': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1489 raised an error (recorded in the `errors` attribute of the result table): '6:01:21.4196 -12:24:07.9932': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1500 raised an error (recorded in the `errors` attribute of the result table): '5:49:05.4114 -12:13:58.944': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1511 raised an error (recorded in the `errors` attribute of the result table): '5:59:27.0082 -12:30:46.6908': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1515 raised an error (recorded in the `errors` attribute of the result table): '5:59:01.0555 -12:31:45.5122': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1523 raised an error (recorded in the `errors` attribute of the result table): '5:31:17.363 -11:59:12.5083': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1525 raised an error (recorded in the `errors` attribute of the result table): '5:32:55.8142 -12:04:22.3345': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1528 raised an error (recorded in the `errors` attribute of the result table): '5:31:09.7831 -11:43:07.4501': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1530 raised an error (recorded in the `errors` attribute of the result table): '6:02:33.8842 -12:38:05.0404': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1538 raised an error (recorded in the `errors` attribute of the result table): '6:03:40.2701 -12:30:09.0346': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1543 raised an error (recorded in the `errors` attribute of the result table): '6:05:50.4235 -12:40:00.5496': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1546 raised an error (recorded in the `errors` attribute of the result table): '5:39:00.3296 -12:28:53.1322': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1549 raised an error (recorded in the `errors` attribute of the result table): '5:39:17.6251 -12:29:57.5544': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1572 raised an error (recorded in the `errors` attribute of the result table): '6:05:42.7854 -12:49:58.3297': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1575 raised an error (recorded in the `errors` attribute of the result table): '5:46:48.6357 -12:39:30.8201': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1578 raised an error (recorded in the `errors` attribute of the result table): '5:39:13.6299 -12:34:03.3789': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1584 raised an error (recorded in the `errors` attribute of the result table): '5:33:01.0867 -12:27:37.637': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1586 raised an error (recorded in the `errors` attribute of the result table): '6:04:36.1835 -12:49:08.5253': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1592 raised an error (recorded in the `errors` attribute of the result table): '5:52:49.0231 -12:37:36.3185': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1600 raised an error (recorded in the `errors` attribute of the result table): '5:58:14.9856 -12:50:49.4119': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1608 raised an error (recorded in the `errors` attribute of the result table): '5:58:36.8336 -12:50:22.2686': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1612 raised an error (recorded in the `errors` attribute of the result table): '5:35:02.9375 -12:40:10.4208': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1616 raised an error (recorded in the `errors` attribute of the result table): '6:04:36.6336 -12:54:49.7645': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1626 raised an error (recorded in the `errors` attribute of the result table): '5:48:51.1957 -12:51:30.6717': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1631 raised an error (recorded in the `errors` attribute of the result table): '5:32:51.716 -12:41:33.0182': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1636 raised an error (recorded in the `errors` attribute of the result table): '5:35:53.5204 -12:45:32.6241': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1645 raised an error (recorded in the `errors` attribute of the result table): '5:58:42.0951 -13:00:21.9401': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1653 raised an error (recorded in the `errors` attribute of the result table): '5:57:31.8168 -12:50:52.1723': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1667 raised an error (recorded in the `errors` attribute of the result table): '6:02:37.3164 -13:05:32.6312': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1673 raised an error (recorded in the `errors` attribute of the result table): '6:04:02.7171 -13:06:56.2124': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1688 raised an error (recorded in the `errors` attribute of the result table): '5:52:57.8397 -13:05:11.78': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1693 raised an error (recorded in the `errors` attribute of the result table): '5:39:46.0911 -12:50:13.8973': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1701 raised an error (recorded in the `errors` attribute of the result table): '6:02:34.8316 -13:13:58.7512': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1709 raised an error (recorded in the `errors` attribute of the result table): '5:58:21.2142 -13:12:25.4209': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1713 raised an error (recorded in the `errors` attribute of the result table): '5:30:02.8094 -12:53:37.9872': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1716 raised an error (recorded in the `errors` attribute of the result table): '5:51:16.3404 -12:53:42.2305': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1721 raised an error (recorded in the `errors` attribute of the result table): '5:53:40.9211 -13:08:01.9616': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1734 raised an error (recorded in the `errors` attribute of the result table): '6:01:17.0248 -13:20:55.7979': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1741 raised an error (recorded in the `errors` attribute of the result table): '5:58:57.0913 -13:23:26.382': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1744 raised an error (recorded in the `errors` attribute of the result table): '5:45:09.1751 -13:09:37.7403': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1750 raised an error (recorded in the `errors` attribute of the result table): '5:28:24.1953 -13:03:46.9855': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1758 raised an error (recorded in the `errors` attribute of the result table): '5:51:16.2338 -13:15:15.8514': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1764 raised an error (recorded in the `errors` attribute of the result table): '6:00:27.4447 -13:21:23.7478': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1769 raised an error (recorded in the `errors` attribute of the result table): '5:36:45.1219 -13:10:30.2938': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1772 raised an error (recorded in the `errors` attribute of the result table): '5:59:31.3189 -13:24:06.1087': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1786 raised an error (recorded in the `errors` attribute of the result table): '5:23:15.6793 -13:00:50.1795': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1792 raised an error (recorded in the `errors` attribute of the result table): '5:59:36.587 -13:30:09.5998': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1795 raised an error (recorded in the `errors` attribute of the result table): '6:02:43.5033 -13:30:41.4178': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1814 raised an error (recorded in the `errors` attribute of the result table): '6:02:48.8209 -13:34:38.9007': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1821 raised an error (recorded in the `errors` attribute of the result table): '5:58:36.2481 -13:36:20.0423': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1824 raised an error (recorded in the `errors` attribute of the result table): '5:43:12.8233 -13:26:31.6856': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1833 raised an error (recorded in the `errors` attribute of the result table): '5:58:13.4941 -13:35:47.009': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1842 raised an error (recorded in the `errors` attribute of the result table): '5:56:28.2821 -13:37:36.8131': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1845 raised an error (recorded in the `errors` attribute of the result table): '5:47:12.4814 -13:33:53.0635': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1849 raised an error (recorded in the `errors` attribute of the result table): '5:58:20.6227 -13:41:13.8309': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1867 raised an error (recorded in the `errors` attribute of the result table): '5:23:11.8668 -13:16:04.1944': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1875 raised an error (recorded in the `errors` attribute of the result table): '5:42:26.9469 -13:38:16.5155': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1881 raised an error (recorded in the `errors` attribute of the result table): '6:01:20.83 -13:49:25.3813': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1885 raised an error (recorded in the `errors` attribute of the result table): '5:47:59.4964 -13:46:27.2773': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1898 raised an error (recorded in the `errors` attribute of the result table): '5:44:12.4705 -13:46:17.7879': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1905 raised an error (recorded in the `errors` attribute of the result table): '5:45:27.8472 -13:49:44.0118': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1909 raised an error (recorded in the `errors` attribute of the result table): '5:47:23.2219 -13:50:58.2834': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1915 raised an error (recorded in the `errors` attribute of the result table): '6:02:04.6232 -13:57:54.9045': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1924 raised an error (recorded in the `errors` attribute of the result table): '5:56:53.0574 -13:56:34.744': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1930 raised an error (recorded in the `errors` attribute of the result table): '5:57:04.3657 -13:57:52.1817': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1933 raised an error (recorded in the `errors` attribute of the result table): '5:35:02.2356 -13:45:13.8418': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1939 raised an error (recorded in the `errors` attribute of the result table): '5:58:25.7683 -14:02:59.8977': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1941 raised an error (recorded in the `errors` attribute of the result table): '5:41:26.4503 -13:53:34.5302': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1945 raised an error (recorded in the `errors` attribute of the result table): '6:06:43.2875 -14:07:30.0118': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1951 raised an error (recorded in the `errors` attribute of the result table): '5:45:00.9076 -13:58:39.2815': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1955 raised an error (recorded in the `errors` attribute of the result table): '5:41:29.2576 -13:59:02.6253': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1975 raised an error (recorded in the `errors` attribute of the result table): '5:30:18.821 -13:36:13.1743': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1981 raised an error (recorded in the `errors` attribute of the result table): '6:03:44.8783 -14:16:55.9713': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1995 raised an error (recorded in the `errors` attribute of the result table): '5:37:21.5933 -14:02:00.6773': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2000 raised an error (recorded in the `errors` attribute of the result table): '5:36:33.3088 -14:04:01.3337': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2019 raised an error (recorded in the `errors` attribute of the result table): '5:58:49.5866 -14:26:56.0054': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2023 raised an error (recorded in the `errors` attribute of the result table): '6:00:13.5919 -14:25:44.7791': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2031 raised an error (recorded in the `errors` attribute of the result table): '6:04:40.0181 -14:31:36.9435': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2037 raised an error (recorded in the `errors` attribute of the result table): '6:05:04.8303 -14:33:51.1723': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2040 raised an error (recorded in the `errors` attribute of the result table): '5:38:30.146 -13:51:27.3176': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2052 raised an error (recorded in the `errors` attribute of the result table): '5:36:55.6527 -14:17:36.1402': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2055 raised an error (recorded in the `errors` attribute of the result table): '5:40:54.2649 -14:22:52.0318': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2074 raised an error (recorded in the `errors` attribute of the result table): '5:38:26.4287 -14:23:43.3761': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2076 raised an error (recorded in the `errors` attribute of the result table): '5:36:19.9487 -14:22:51.4259': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2083 raised an error (recorded in the `errors` attribute of the result table): '5:49:17.9338 -14:33:44.4131': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2088 raised an error (recorded in the `errors` attribute of the result table): '5:47:54.7627 -14:31:06.3449': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2094 raised an error (recorded in the `errors` attribute of the result table): '5:42:43.917 -14:32:30.8836': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2109 raised an error (recorded in the `errors` attribute of the result table): '5:59:01.367 -14:40:07.0515': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2120 raised an error (recorded in the `errors` attribute of the result table): '6:01:24.2032 -14:48:41.9362': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2127 raised an error (recorded in the `errors` attribute of the result table): '5:29:04.0816 -14:25:15.4746': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2132 raised an error (recorded in the `errors` attribute of the result table): '5:57:40.5452 -14:44:23.3547': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2149 raised an error (recorded in the `errors` attribute of the result table): '5:48:06.7942 -14:41:47.8065': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2161 raised an error (recorded in the `errors` attribute of the result table): '5:56:23.035 -14:15:50.4645': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2166 raised an error (recorded in the `errors` attribute of the result table): '5:41:46.7664 -14:41:46.7697': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2173 raised an error (recorded in the `errors` attribute of the result table): '5:29:42.1011 -14:34:29.9318': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2176 raised an error (recorded in the `errors` attribute of the result table): '6:04:34.4377 -14:57:05.6067': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2180 raised an error (recorded in the `errors` attribute of the result table): '6:03:02.1951 -14:49:31.4183': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2182 raised an error (recorded in the `errors` attribute of the result table): '5:58:25.6806 -14:58:06.8966': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2184 raised an error (recorded in the `errors` attribute of the result table): '6:02:31.7438 -15:00:26.7823': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2193 raised an error (recorded in the `errors` attribute of the result table): '5:57:44.9941 -14:58:43.0376': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2208 raised an error (recorded in the `errors` attribute of the result table): '6:02:08.3227 -15:04:51.0852': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2213 raised an error (recorded in the `errors` attribute of the result table): '6:03:05.4659 -15:01:41.6537': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2217 raised an error (recorded in the `errors` attribute of the result table): '5:22:20.2934 -14:39:04.8036': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2220 raised an error (recorded in the `errors` attribute of the result table): '6:00:20.6131 -15:05:04.0601': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2226 raised an error (recorded in the `errors` attribute of the result table): '6:03:53.9469 -15:09:26.3616': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2237 raised an error (recorded in the `errors` attribute of the result table): '6:05:42.1237 -15:09:04.5894': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2245 raised an error (recorded in the `errors` attribute of the result table): '5:56:16.7955 -15:10:43.9969': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2247 raised an error (recorded in the `errors` attribute of the result table): '5:46:02.4626 -15:04:06.3952': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2256 raised an error (recorded in the `errors` attribute of the result table): '6:05:16.7151 -15:17:20.1164': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2262 raised an error (recorded in the `errors` attribute of the result table): '5:34:38.9309 -15:01:06.2779': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2274 raised an error (recorded in the `errors` attribute of the result table): '5:28:56.6478 -15:01:32.4247': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2280 raised an error (recorded in the `errors` attribute of the result table): '6:01:46.2571 -15:23:55.4338': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2287 raised an error (recorded in the `errors` attribute of the result table): '5:28:15.9678 -15:03:44.1601': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2292 raised an error (recorded in the `errors` attribute of the result table): '5:38:14.9966 -15:12:32.6846': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2301 raised an error (recorded in the `errors` attribute of the result table): '5:38:54.4224 -15:17:27.6762': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2313 raised an error (recorded in the `errors` attribute of the result table): '5:25:37.6902 -15:05:22.4564': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2315 raised an error (recorded in the `errors` attribute of the result table): '5:51:00.541 -15:25:51.1774': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2318 raised an error (recorded in the `errors` attribute of the result table): '6:02:44.6112 -15:32:52.4318': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2339 raised an error (recorded in the `errors` attribute of the result table): '5:54:54.131 -15:37:41.2091': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2352 raised an error (recorded in the `errors` attribute of the result table): '6:01:59.07 -15:45:37.4305': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2365 raised an error (recorded in the `errors` attribute of the result table): '5:44:22.8052 -15:37:08.0625': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2384 raised an error (recorded in the `errors` attribute of the result table): '5:44:38.91 -15:42:16.9409': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2398 raised an error (recorded in the `errors` attribute of the result table): '6:02:15.8586 -15:50:31.3659': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2402 raised an error (recorded in the `errors` attribute of the result table): '6:02:34.8517 -15:55:15.3838': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2407 raised an error (recorded in the `errors` attribute of the result table): '5:58:22.6937 -15:47:57.7828': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2413 raised an error (recorded in the `errors` attribute of the result table): '5:38:30.8756 -15:41:11.569': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2421 raised an error (recorded in the `errors` attribute of the result table): '5:53:15.1843 -15:54:16.9806': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2425 raised an error (recorded in the `errors` attribute of the result table): '5:44:42.7273 -15:49:45.9831': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2432 raised an error (recorded in the `errors` attribute of the result table): '6:01:20.9786 -15:46:53.8296': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2438 raised an error (recorded in the `errors` attribute of the result table): '5:38:59.6123 -15:40:53.385': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2450 raised an error (recorded in the `errors` attribute of the result table): '6:02:53.4048 -15:58:28.6456': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2453 raised an error (recorded in the `errors` attribute of the result table): '5:50:44.5101 -15:55:12.3485': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2465 raised an error (recorded in the `errors` attribute of the result table): '6:01:43.639 -16:08:17.4989': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2471 raised an error (recorded in the `errors` attribute of the result table): '5:27:49.5091 -15:43:10.7256': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2474 raised an error (recorded in the `errors` attribute of the result table): '5:27:07.502 -15:39:31.5702': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2491 raised an error (recorded in the `errors` attribute of the result table): '5:21:10.8081 -15:38:40.5108': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2500 raised an error (recorded in the `errors` attribute of the result table): '5:45:22.7356 -16:05:20.518': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2510 raised an error (recorded in the `errors` attribute of the result table): '5:48:49.6892 -15:53:15.7208': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2524 raised an error (recorded in the `errors` attribute of the result table): '5:55:16.3293 -16:14:50.7978': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2528 raised an error (recorded in the `errors` attribute of the result table): '5:43:55.9988 -16:09:54.0997': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2535 raised an error (recorded in the `errors` attribute of the result table): '6:02:05.7237 -16:16:14.7083': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2545 raised an error (recorded in the `errors` attribute of the result table): '6:04:37.4711 -16:19:13.2679': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2550 raised an error (recorded in the `errors` attribute of the result table): '6:01:58.447 -16:22:22.9964': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2558 raised an error (recorded in the `errors` attribute of the result table): '5:34:47.8916 -16:02:39.1908': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2566 raised an error (recorded in the `errors` attribute of the result table): '6:03:47.8026 -16:18:49.0863': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2568 raised an error (recorded in the `errors` attribute of the result table): '5:40:21.0398 -16:11:14.2048': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2576 raised an error (recorded in the `errors` attribute of the result table): '5:56:16.1626 -16:20:16.3474': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2579 raised an error (recorded in the `errors` attribute of the result table): '5:52:48.2593 -16:13:20.2533': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2583 raised an error (recorded in the `errors` attribute of the result table): '5:52:02.0975 -16:21:33.4352': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2586 raised an error (recorded in the `errors` attribute of the result table): '5:51:48.4925 -16:23:33.3662': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2590 raised an error (recorded in the `errors` attribute of the result table): '5:54:48.9671 -16:25:17.377': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2607 raised an error (recorded in the `errors` attribute of the result table): '6:03:36.2319 -16:32:45.0899': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2611 raised an error (recorded in the `errors` attribute of the result table): '5:34:46.997 -16:14:43.2781': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2620 raised an error (recorded in the `errors` attribute of the result table): '5:27:30.8109 -16:12:29.8551': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2630 raised an error (recorded in the `errors` attribute of the result table): '5:50:33.6703 -16:23:23.7406': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2634 raised an error (recorded in the `errors` attribute of the result table): '5:45:58.7901 -16:28:22.4686': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2641 raised an error (recorded in the `errors` attribute of the result table): '5:20:25.0435 -16:11:38.7575': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2643 raised an error (recorded in the `errors` attribute of the result table): '5:57:07.2718 -16:41:53.4466': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2646 raised an error (recorded in the `errors` attribute of the result table): '6:02:56.0863 -16:39:46.5148': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2654 raised an error (recorded in the `errors` attribute of the result table): '5:38:03.1143 -16:32:42.5069': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2656 raised an error (recorded in the `errors` attribute of the result table): '5:59:13.1106 -16:44:57.859': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2669 raised an error (recorded in the `errors` attribute of the result table): '5:52:29.1415 -16:44:48.9074': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2680 raised an error (recorded in the `errors` attribute of the result table): '5:25:50.6722 -16:24:56.7412': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2685 raised an error (recorded in the `errors` attribute of the result table): '5:20:03.4602 -16:20:06.5395': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2693 raised an error (recorded in the `errors` attribute of the result table): '5:26:29.4969 -16:26:18.481': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2701 raised an error (recorded in the `errors` attribute of the result table): '5:49:41.1602 -16:46:40.2128': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2705 raised an error (recorded in the `errors` attribute of the result table): '5:58:20.1099 -16:56:39.0476': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2713 raised an error (recorded in the `errors` attribute of the result table): '5:41:24.3877 -16:47:09.5772': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2720 raised an error (recorded in the `errors` attribute of the result table): '5:48:32.4783 -16:53:46.992': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2725 raised an error (recorded in the `errors` attribute of the result table): '5:19:30.152 -16:27:24.1937': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2734 raised an error (recorded in the `errors` attribute of the result table): '6:05:07.9764 -16:59:18.43': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2743 raised an error (recorded in the `errors` attribute of the result table): '5:57:58.5224 -17:03:07.8762': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2758 raised an error (recorded in the `errors` attribute of the result table): '5:33:34.1484 -16:42:53.5132': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2783 raised an error (recorded in the `errors` attribute of the result table): '5:44:21.9598 -16:58:00.3572': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2788 raised an error (recorded in the `errors` attribute of the result table): '5:58:31.1547 -17:09:21.8311': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2798 raised an error (recorded in the `errors` attribute of the result table): '5:46:07.7664 -17:01:27.4328': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2801 raised an error (recorded in the `errors` attribute of the result table): '5:20:01.8887 -16:41:23.7371': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2807 raised an error (recorded in the `errors` attribute of the result table): '5:37:17.7725 -16:46:55.2371': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2813 raised an error (recorded in the `errors` attribute of the result table): '6:02:21.2872 -17:15:29.2114': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2825 raised an error (recorded in the `errors` attribute of the result table): '6:01:28.0131 -17:50:10.3165': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2836 raised an error (recorded in the `errors` attribute of the result table): '5:29:38.5774 -17:29:41.868': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2846 raised an error (recorded in the `errors` attribute of the result table): '5:49:41.1132 -17:21:30.148': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2891 raised an error (recorded in the `errors` attribute of the result table): '5:39:43.9978 -17:28:43.58': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2896 raised an error (recorded in the `errors` attribute of the result table): '5:38:19.5307 -17:06:03.9083': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2906 raised an error (recorded in the `errors` attribute of the result table): '5:27:55.7025 -17:01:17.7597': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2932 raised an error (recorded in the `errors` attribute of the result table): '5:27:54.8834 -16:58:52.5041': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2943 raised an error (recorded in the `errors` attribute of the result table): '6:05:05.7688 -17:35:40.6027': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2953 raised an error (recorded in the `errors` attribute of the result table): '5:44:50.4263 -17:49:39.8749': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2959 raised an error (recorded in the `errors` attribute of the result table): '5:25:07.1941 -17:09:55.1325': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2964 raised an error (recorded in the `errors` attribute of the result table): '5:44:23.6072 -17:41:25.8852': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2968 raised an error (recorded in the `errors` attribute of the result table): '5:27:25.4463 -17:12:50.1192': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2982 raised an error (recorded in the `errors` attribute of the result table): '5:57:44.2566 -17:39:36.5671': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2988 raised an error (recorded in the `errors` attribute of the result table): '5:53:33.3921 -17:41:41.1879': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2990 raised an error (recorded in the `errors` attribute of the result table): '5:50:10.8739 -17:37:55.1837': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2996 raised an error (recorded in the `errors` attribute of the result table): '5:24:09.2921 -16:49:57.2642': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3000 raised an error (recorded in the `errors` attribute of the result table): '5:58:32.9906 -17:47:28.9851': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3013 raised an error (recorded in the `errors` attribute of the result table): '5:54:19.7443 -17:23:18.6633': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3021 raised an error (recorded in the `errors` attribute of the result table): '6:00:38.7154 -17:24:56.1814': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3025 raised an error (recorded in the `errors` attribute of the result table): '5:39:06.1108 -17:25:18.7349': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3036 raised an error (recorded in the `errors` attribute of the result table): '5:59:44.2704 -17:31:54.5374': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3041 raised an error (recorded in the `errors` attribute of the result table): '5:50:56.0586 -17:43:19.4852': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3060 raised an error (recorded in the `errors` attribute of the result table): '5:51:29.5297 -17:29:25.4088': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3066 raised an error (recorded in the `errors` attribute of the result table): '5:25:47.9396 -17:08:57.7206': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3071 raised an error (recorded in the `errors` attribute of the result table): '5:43:28.2921 -17:40:27.0828': No astronomical object found :\n",
      "  (error.line, error.msg))\n"
     ]
    }
   ],
   "source": [
    "result_table = Simbad.query_region(orig_coord,\n",
    "                                   radius=search_radius)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "3544"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(result_table)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "3074"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(orig_coord)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'-6:28:39.4625'"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "result_table.errors[0].msg.split(' ')[1][:-2]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "?result_table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
